package dev.omatube.app.backend

import com.google.gson.JsonElement
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import dev.omatube.app.model.TranscriptCue
import dev.omatube.app.model.TranscriptWord
import okhttp3.HttpUrl
import okhttp3.HttpUrl.Companion.toHttpUrlOrNull
import org.schabi.newpipe.extractor.stream.DeliveryMethod
import org.schabi.newpipe.extractor.stream.StreamInfo
import org.schabi.newpipe.extractor.stream.SubtitlesStream
import java.io.IOException
import java.util.Locale

/** Downloads and parses one preferred YouTube caption track from resolved stream metadata. */
class YoutubeTranscriptLoader(
    private val transport: HttpTransport,
    private val userAgent: String = NewPipeBackend.USER_AGENT,
    private val localeProvider: () -> Locale = Locale::getDefault,
) {
    fun load(streamInfo: StreamInfo): List<TranscriptCue> {
        val subtitle = selectTrack(streamInfo.subtitles ?: emptyList()) ?: return emptyList()
        return loadTrack(subtitle)
    }

    internal fun loadTrack(subtitle: SubtitlesStream): List<TranscriptCue> {
        val url = subtitle.content.toHttpUrlOrNull()
            ?.takeIf { it.scheme == "http" || it.scheme == "https" }
            ?: return emptyList()
        val response = transport.execute(
            method = "GET",
            url = rewriteFormat(url).toString(),
            headers = mapOf(
                "User-Agent" to listOf(userAgent),
                "Accept" to listOf("application/json"),
            ),
            maxResponseBytes = MAX_RESPONSE_BYTES,
        )
        if (response.code !in 200..299) {
            throw IOException("Transcript request failed with HTTP ${response.code}.")
        }
        return parse(response.bodyText())
    }

    fun selectTrack(tracks: List<SubtitlesStream>): SubtitlesStream? {
        val locale = localeProvider()
        return tracks.asSequence()
            .filter { it.isUsable() }
            .sortedWith(compareBy<SubtitlesStream> {
                val tag = it.languageTag.lowercase(Locale.ROOT)
                when {
                    tag == locale.toLanguageTag().lowercase(Locale.ROOT) -> 0
                    tag.substringBefore('-') == locale.language.lowercase(Locale.ROOT) -> 1
                    tag.substringBefore('-') == "en" -> 2
                    else -> 3
                }
            }.thenBy { if (it.isAutoGenerated) 1 else 0 })
            .firstOrNull()
    }

    companion object {
        const val MAX_RESPONSE_BYTES: Long = HttpTransport.DEFAULT_MAX_RESPONSE_BYTES

        fun rewriteFormat(url: HttpUrl): HttpUrl = url.newBuilder()
            .setQueryParameter("fmt", "json3")
            .build()

        fun parse(body: String): List<TranscriptCue> {
            val root = try {
                JsonParser.parseString(body).asJsonObject
            } catch (e: RuntimeException) {
                throw IOException("Transcript response is not valid JSON.", e)
            }
            val events = root.get("events")?.takeIf { it.isJsonArray }?.asJsonArray
                ?: return emptyList()
            val parsed = ArrayList<ParsedEvent>()
            for (index in 0 until minOf(events.size(), MAX_EVENTS)) {
                val event = events[index].asObjectOrNull() ?: continue
                val start = nonNegativeLong(event, "tStartMs") ?: continue
                if (start == Long.MAX_VALUE) continue
                val duration = nonNegativeLong(event, "dDurationMs")?.takeIf { it > 0L }
                val end = duration?.let { safeAdd(start, it) }
                val segments = event.get("segs")?.takeIf { it.isJsonArray }?.asJsonArray
                    ?: continue
                val words = ArrayList<SegmentWords>()
                for (segmentIndex in 0 until minOf(segments.size(), MAX_SEGMENTS_PER_EVENT)) {
                    val segment = segments[segmentIndex].asObjectOrNull() ?: continue
                    val text = segment.get("utf8")?.takeIf { it.isJsonPrimitive && it.asJsonPrimitive.isString }
                        ?.asString?.normalizeWords() ?: continue
                    if (text.isEmpty()) continue
                    val segmentStart = safeAdd(start, nonNegativeLong(segment, "tOffsetMs") ?: 0L)
                    words += SegmentWords(segmentStart, text.split(' '))
                }
                if (words.isNotEmpty()) parsed += ParsedEvent(start, end, words)
            }
            val sorted = parsed.sortedWith(
                compareBy<ParsedEvent> { it.start }.thenBy { it.end ?: Long.MAX_VALUE },
            )
            val nextStartByStart = sorted
                .map { it.start }
                .distinct()
                .zipWithNext()
                .associate { (start, nextStart) -> start to nextStart }
            return sorted.map { event ->
                val cueEnd = event.end
                    ?.takeIf { it > event.start }
                    ?: nextStartByStart[event.start]
                    ?: positiveEnd(event.start, event.start)
                val transcriptWords = event.words.flatMapIndexed { index, segment ->
                    val nextStart = event.words.getOrNull(index + 1)?.start ?: cueEnd
                    val span = maxOf(0L, nextStart - segment.start)
                    segment.words.mapIndexed { wordIndex, word ->
                        val wordStart = segment.start + if (segment.words.size == 1) {
                            0L
                        } else {
                            val count = segment.words.size.toLong()
                            (span / count) * wordIndex + (span % count) * wordIndex / count
                        }
                        TranscriptWord(word, wordStart.coerceIn(event.start, cueEnd - 1))
                    }
                }
                TranscriptCue(event.start, cueEnd, transcriptWords)
            }.filter { it.words.isNotEmpty() }
        }

        private const val MAX_EVENTS = 10_000
        private const val MAX_SEGMENTS_PER_EVENT = 1_000

        private data class ParsedEvent(
            val start: Long,
            val end: Long?,
            val words: List<SegmentWords>,
        )
        private data class SegmentWords(val start: Long, val words: List<String>)

        private fun JsonElement.asObjectOrNull(): JsonObject? =
            if (isJsonObject) asJsonObject else null

        private fun nonNegativeLong(objectValue: JsonObject, name: String): Long? =
            objectValue.get(name)?.takeIf { it.isJsonPrimitive }?.let {
                try { it.asLong.coerceAtLeast(0L) } catch (_: RuntimeException) { null }
            }

        private fun safeAdd(first: Long, second: Long): Long =
            if (Long.MAX_VALUE - first < second) Long.MAX_VALUE else first + second

        private fun positiveEnd(start: Long, end: Long): Long =
            if (end > start) end else if (start == Long.MAX_VALUE) Long.MAX_VALUE else start + 1

        private fun String.normalizeWords(): String = trim().replace(Regex("\\s+"), " ")

        private fun SubtitlesStream.isUsable(): Boolean =
            isUrl && deliveryMethod != DeliveryMethod.TORRENT &&
                content.toHttpUrlOrNull()?.let { it.scheme == "http" || it.scheme == "https" } == true
    }
}
